//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FakeOReal.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames
    {
        /// <summary>
        /// Event fired to tell the shell to update the status panel
        /// </summary>
        public const string StatusUpdate = "StatusUpdate";
        public const string LoadImage = "LoadImage";
        public const string SetAParam = "SetAParam";
        public const string OnEnchance = "OnEnchance";
       // public const string SetAnalysisParam = "SetAnalysisParam";
    }
}
