//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// This class contains placeholder methods for the common module initialization 
// tasks, such as adding services, or user-interface element
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using FakeOReal.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.Commands;
using Microsoft.Practices.CompositeUI.EventBroker;
using FakeOReal.Detect.Constants;
using System.Drawing;
using Microsoft.Practices.CompositeUI.SmartParts;
using System.Security.Cryptography;
using System.Drawing.Imaging;

namespace FakeOReal.Detect
{
    public class ModuleController : WorkItemController
    {
        private static Image image1;
       // private static Image image2;
        private static string path;
        private static ushort[] temparr = new ushort[64];
       // private static DetectView1 dv;
       // private static QView qv;

        public override void Run()
        {
            AddServices();
            ExtendMenu();
            ExtendToolStrip();
            AddViews();
        }

        private void AddServices()
        {
           
        }

        private void ExtendMenu()
        {
            //TODO: add menu items here, normally by calling the "Add" method on           
            UIExtensionSite MainMenuSite = this.WorkItem.UIExtensionSites[UIExtensionSiteNames.MainMenu];
            ToolStripMenuItem TopTi = new ToolStripMenuItem("Source Detection");
            ToolStripMenuItem ti1 = new ToolStripMenuItem("Detect Origin");
            ToolStripMenuItem ti2 = new ToolStripMenuItem("Ballastics Testing");
            TopTi.DropDownItems.Add(ti1);
            TopTi.DropDownItems.Add(ti2);            
            MainMenuSite.Add(TopTi);
            this.WorkItem.Commands[CommandNames._detect_source].
        AddInvoker(ti1, "Click");
            this.WorkItem.Commands[CommandNames._ballistics_testing].
        AddInvoker(ti2, "Click");            
        }

        private void ExtendToolStrip()
        {
            UIExtensionSite MainToolbarSite =
        this.WorkItem.UIExtensionSites[UIExtensionSiteNames.MainToolbar];

            ToolStripButton ts = new ToolStripButton();
            Image im = Image.FromFile("missilel.png");
            ts.Image = im;
            MainToolbarSite.Add(ts);

            ToolStripButton ts1 = new ToolStripButton();
            Image im1 = Image.FromFile("quant.gif");
            ts1.Image = im1;
            MainToolbarSite.Add(ts1);

            ToolStripSeparator sp = new ToolStripSeparator();
            MainToolbarSite.Add(sp);

            ts.ToolTipText = "Ballistic Testing";
            ts1.ToolTipText = "Detect Origin";

            this.WorkItem.Commands[CommandNames._ballistics_testing].
        AddInvoker(ts, "Click");
            this.WorkItem.Commands[CommandNames._detect_source].
        AddInvoker(ts1, "Click");
            
        }

        private void AddViews()
        {          

        }

        [EventSubscription(EventTopicNames.LoadImage, ThreadOption.UserInterface)]
        public void OnLoadImage(object sender, OnImageLoad eventArgs)
        {
            image1 = eventArgs.img;
            path = eventArgs.file;
        }

        [CommandHandler(CommandNames._ballistics_testing)]
        public void BallisticsClickHandler(object sender, EventArgs e)
        {            
            if (image1 != null)
            {
                BallisticView dv = this.WorkItem.SmartParts.AddNew<BallisticView>();
                BallisticView.image = image1;
                dv.pictureBox1.Image = image1;
                int s = path.LastIndexOf('\\');
                dv.imageLabel1.Text = path.Substring(path.LastIndexOf('\\') + 1, ((path.Length - 1) - path.LastIndexOf('\\')));                    
                SmartPartInfo spi =
                     new SmartPartInfo("Ballistics Test", "MyOwnDescription");
                this.WorkItem.Workspaces[WorkspaceNames.TabWorkspace].Show(dv, spi);
            }           
        }

        [CommandHandler(CommandNames._detect_source)]
        public void OriginClickHandler(object sender, EventArgs e)
        {
            if (image1 != null)
            {
                Image image = new Bitmap(path);
                string make = null;
                string model = null;
                string quality = null;
                string software = null;
               // QView qv = this.WorkItem.SmartParts.AddNew<QView>();     
                PropertyItem[] propItems = image.PropertyItems;
                System.Text.ASCIIEncoding encoding = new System.Text.ASCIIEncoding();
                try
                {
                     make = encoding.GetString(image.GetPropertyItem(0x010F).Value);
                     model = encoding.GetString(image.GetPropertyItem(0x0110).Value);                     
                     software = encoding.GetString(image.GetPropertyItem(0x0131).Value);
                     quality = encoding.GetString(image.GetPropertyItem(0x5010).Value);                     
                }catch(Exception){
                
                }               
                byte[] lumi = image.GetPropertyItem(0x5090).Value;                
                byte[] chro = image.GetPropertyItem(0x5091).Value;
                byte[] data = new byte[256];
                Array.Copy(lumi,0,data,0,128);
                Array.Copy(chro, 0, data, 128, 128);
                MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();           
                for (int i =0; i < lumi.Length / 2; i++)
                {                  
                    temparr[i] = BitConverter.ToUInt16(lumi, 2 * i);
                   // setTable1(qv);                   
                }             
                for (int i = 0; i < chro.Length / 2; i++)
                {       
                    temparr[i] = BitConverter.ToUInt16(chro, 2 * i);
                  //  setTable2(qv);
                }
                byte[] hash = md5.ComputeHash(data);
                string hashedValue = "";
                foreach (byte b in hash)
                {
                    hashedValue += b.ToString("x2");
                }            
               // qv.sign1.Text = hashedValue;
                SmartPartInfo spi =
                     new SmartPartInfo("Source Detection", "MyOwnDescription");
                //this.WorkItem.Workspaces[WorkspaceNames.TabWorkspace].Show(qv, spi);
                MySQLConnectionTest conn2 = new MySQLConnectionTest();
                conn2.DBSelect(this,hashedValue,software,make,model,quality);
            }
        }       

        private void setTable1(QView qv) { 
             qv.label1.Text = temparr[0].ToString();
             qv.label2.Text = temparr[1].ToString();
             qv.label3.Text = temparr[2].ToString();
             qv.label4.Text = temparr[3].ToString();
             qv.label5.Text = temparr[4].ToString();
             qv.label6.Text = temparr[5].ToString();
             qv.label7.Text = temparr[6].ToString();
             qv.label8.Text = temparr[7].ToString();
             qv.label9.Text = temparr[8].ToString();
             qv.label10.Text = temparr[9].ToString();
             qv.label11.Text = temparr[10].ToString();
             qv.label12.Text = temparr[11].ToString();
             qv.label13.Text = temparr[12].ToString();
             qv.label14.Text = temparr[13].ToString();
             qv.label15.Text = temparr[14].ToString();
             qv.label16.Text = temparr[15].ToString();
             qv.label17.Text = temparr[16].ToString();
             qv.label18.Text = temparr[17].ToString();
             qv.label19.Text = temparr[18].ToString();
             qv.label20.Text = temparr[19].ToString();
             qv.label21.Text = temparr[20].ToString();
             qv.label22.Text = temparr[21].ToString();
             qv.label23.Text = temparr[22].ToString();
             qv.label24.Text = temparr[23].ToString();
             qv.label25.Text = temparr[24].ToString();
             qv.label26.Text = temparr[25].ToString();
             qv.label27.Text = temparr[26].ToString();
             qv.label28.Text = temparr[27].ToString();
             qv.label29.Text = temparr[28].ToString();
             qv.label30.Text = temparr[29].ToString();
             qv.label31.Text = temparr[30].ToString();
             qv.label32.Text = temparr[31].ToString();
             qv.label33.Text = temparr[32].ToString();
             qv.label34.Text = temparr[33].ToString();
             qv.label35.Text = temparr[34].ToString();
             qv.label36.Text = temparr[35].ToString();
             qv.label37.Text = temparr[36].ToString();
             qv.label38.Text = temparr[37].ToString();
             qv.label39.Text = temparr[38].ToString();
             qv.label40.Text = temparr[39].ToString();
             qv.label41.Text = temparr[40].ToString();
             qv.label42.Text = temparr[41].ToString();
             qv.label43.Text = temparr[42].ToString();
             qv.label44.Text = temparr[43].ToString();
             qv.label45.Text = temparr[44].ToString();
             qv.label46.Text = temparr[45].ToString();
             qv.label47.Text = temparr[46].ToString();
             qv.label48.Text = temparr[47].ToString();
             qv.label49.Text = temparr[48].ToString();
             qv.label50.Text = temparr[49].ToString();
             qv.label51.Text = temparr[50].ToString();
             qv.label52.Text = temparr[51].ToString();
             qv.label53.Text = temparr[52].ToString();
             qv.label54.Text = temparr[53].ToString();
             qv.label55.Text = temparr[54].ToString();
             qv.label56.Text = temparr[55].ToString();
             qv.label57.Text = temparr[56].ToString();
             qv.label58.Text = temparr[57].ToString();
             qv.label59.Text = temparr[58].ToString();
             qv.label60.Text = temparr[59].ToString();
             qv.label61.Text = temparr[60].ToString();
             qv.label62.Text = temparr[61].ToString();
             qv.label63.Text = temparr[62].ToString();
             qv.label64.Text = temparr[63].ToString();
        }

        private void setTable2(QView qv)
        {
            qv.label65.Text = temparr[0].ToString();
            qv.label66.Text = temparr[1].ToString();
            qv.label67.Text = temparr[2].ToString();
            qv.label68.Text = temparr[3].ToString();
            qv.label69.Text = temparr[4].ToString();
            qv.label70.Text = temparr[5].ToString();
            qv.label71.Text = temparr[6].ToString();
            qv.label72.Text = temparr[7].ToString();
            qv.label73.Text = temparr[8].ToString();
            qv.label74.Text = temparr[9].ToString();
            qv.label75.Text = temparr[10].ToString();
            qv.label76.Text = temparr[11].ToString();
            qv.label77.Text = temparr[12].ToString();
            qv.label78.Text = temparr[13].ToString();
            qv.label79.Text = temparr[14].ToString();
            qv.label80.Text = temparr[15].ToString();
            qv.label81.Text = temparr[16].ToString();
            qv.label82.Text = temparr[17].ToString();
            qv.label83.Text = temparr[18].ToString();
            qv.label84.Text = temparr[19].ToString();
            qv.label85.Text = temparr[20].ToString();
            qv.label86.Text = temparr[21].ToString();
            qv.label87.Text = temparr[22].ToString();
            qv.label88.Text = temparr[23].ToString();
            qv.label89.Text = temparr[24].ToString();
            qv.label90.Text = temparr[25].ToString();
            qv.label91.Text = temparr[26].ToString();
            qv.label92.Text = temparr[27].ToString();
            qv.label93.Text = temparr[28].ToString();
            qv.label94.Text = temparr[29].ToString();
            qv.label95.Text = temparr[30].ToString();
            qv.label96.Text = temparr[31].ToString();
            qv.label97.Text = temparr[32].ToString();
            qv.label98.Text = temparr[33].ToString();
            qv.label99.Text = temparr[34].ToString();
            qv.label100.Text = temparr[35].ToString();
            qv.label101.Text = temparr[36].ToString();
            qv.label102.Text = temparr[37].ToString();
            qv.label103.Text = temparr[38].ToString();
            qv.label104.Text = temparr[39].ToString();
            qv.label105.Text = temparr[40].ToString();
            qv.label106.Text = temparr[41].ToString();
            qv.label107.Text = temparr[42].ToString();
            qv.label108.Text = temparr[43].ToString();
            qv.label109.Text = temparr[44].ToString();
            qv.label110.Text = temparr[45].ToString();
            qv.label111.Text = temparr[46].ToString();
            qv.label112.Text = temparr[47].ToString();
            qv.label113.Text = temparr[48].ToString();
            qv.label114.Text = temparr[49].ToString();
            qv.label115.Text = temparr[50].ToString();
            qv.label116.Text = temparr[51].ToString();
            qv.label117.Text = temparr[52].ToString();
            qv.label118.Text = temparr[53].ToString();
            qv.label119.Text = temparr[54].ToString();
            qv.label120.Text = temparr[55].ToString();
            qv.label121.Text = temparr[56].ToString();
            qv.label122.Text = temparr[57].ToString();
            qv.label123.Text = temparr[58].ToString();
            qv.label124.Text = temparr[59].ToString();
            qv.label125.Text = temparr[60].ToString();
            qv.label126.Text = temparr[61].ToString();
            qv.label127.Text = temparr[62].ToString();
            qv.label128.Text = temparr[63].ToString();
        }
    }
}

