//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// This class is the concrete implementation of a View in the Model-View-Presenter 
// pattern. Communication between the Presenter and this class is acheived through 
// an interface to facilitate separation and testability.
// Note that the Presenter generated by the same recipe, will automatically be created
// by CAB through [CreateNew] and bidirectional references will be added.
//
// For more information see:
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using Microsoft.Practices.CompositeUI.SmartParts;
using Microsoft.Practices.ObjectBuilder;
using FakeOReal.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI.EventBroker;
using FakeOReal.ImageEnchancement.Constants;
using FakeOReal.ImageEnchancement.Interface;

namespace FakeOReal.ImageEnchancement
{
    public partial class ParamView : UserControl, IParamView
    {
        [EventPublication(EventTopicNames.OnEnchance, PublicationScope.WorkItem)]
        public event EventHandler<FakeOReal.ImageEnchancement.Interface.OnEnchanceParam> OnEnchance;
    
        public ParamView()
        {
            InitializeComponent();
        }

        protected override void OnLoad(EventArgs e)
        {
            _presenter.OnViewReady();
            base.OnLoad(e);
        }

        private void button1_Click(object sender, EventArgs e)
        {            
            OnOnEnchance(new OnEnchanceParam(trackBar1.Value,trackBar2.Value,trackBar3.Value));            
        }

        protected virtual void OnOnEnchance(FakeOReal.ImageEnchancement.Interface.OnEnchanceParam eventArgs)
        {
            if (OnEnchance != null)            {
                
                OnEnchance(this, eventArgs);
            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            OnOnEnchance(new OnEnchanceParam(trackBar1.Value, trackBar2.Value, trackBar3.Value));            
        }

        private void button3_Click(object sender, EventArgs e)
        {
            OnOnEnchance(new OnEnchanceParam(trackBar1.Value, trackBar2.Value, trackBar3.Value));          
        }               
    }
}

