//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" or "Add Foundational Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/03-01-020-How_to_Create_a_Business_Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FakeOReal.ImageAnalysis.Interface.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames : FakeOReal.Infrastructure.Interface.Constants.CommandNames
    {
        public const string edge_canny = "Canny";
        public const string edge_sobel = "Sobel";
        public const string edge_difference = "Difference";
        public const string edge_homogenity = "Homogenity";
        public const string edges = "Edges";
        public const string histogram = "Histogram";
        public const string fourier = "Fourier Transformation";        
    }
}
