//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" or "Add Foundational Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/03-01-020-How_to_Create_a_Business_Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace FakeOReal.ImageEnchancement.Interface.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames : FakeOReal.Infrastructure.Interface.Constants.CommandNames
    {
        public const string smooth_gaussian = "Gaussian Smooth";
        public const string smooth_median = "Median Smooth ";
        public const string smooth_adaptive = "Adaptive Smooth";
        public const string smooth_blur = "Blur Smooth";
        public const string smooth_conservative = "Conservative Smooth";
        public const string gamma_correction = "Gamma Correction";
        public const string brightness = "Brightness";
        public const string contrast = "Contrast";
        public const string hue = "HUE";
        public const string invert = "Invert";
        public const string sharpen= "Sharpen";
        public const string convolution = "Convolution";
    }
}
